### ISSUE TITLE
Error when using yup validation on arrays

### ISSUE THREAD

**Issue by batusai513** [jaredpalmer/formik#1692]
### Current Behavior

using the following validation schema sometime the library throws an error when it's trying to update the errors object because the current error field is mutating from an array to a string:
```js
export default yup.object({
  title: yup
    .string()
    .required(requiredMessage)
    .max(maxLength, maxMessage),
  options: yup
    .array()
    .of(
      yup.object().shape({
        question: yup
          .string()
          .required(requiredMessage)
          .min(3, 'Question must be longer than or equal to 3 characters')
          .max(maxLength, maxMessage),
        isTrue: yup
          .string()
          .required(
            'This question need to have at least one correct answer selected'
          ),
        answers: yup
          .array()
          .of(
            yup.object().shape({
              answer: yup
                .string()
                .required(requiredMessage)
                .min(3, 'Answer must be longer than or equal to 3 characters')
                .max(maxLength, maxMessage),
            })
          )
          .min(1, 'add at least one answer'),
      })
    )
    .min(2, 'add at least two questions'),
});
```

```
"TypeError: Cannot assign to read only property '0' of string 'add at least two questions'
    at setIn (http://localhost:3000/static/js/2.chunk.js:661:36)
    at Formik.<anonymous> (http://localhost:3000/static/js/2.chunk.js:1569:33)
    at getStateFromUpdate (http://localhost:3000/static/js/18.chunk.js:30671:40)
    at processUpdateQueue (http://localhost:3000/static/js/18.chunk.js:30735:25)
    at updateClassInstance (http://localhost:3000/static/js/18.chunk.js:25834:9)
    at updateClassComponent (http://localhost:3000/static/js/18.chunk.js:29009:24)
    at beginWork (http://localhost:3000/static/js/18.chunk.js:30000:20)
    at performUnitOfWork (http://localhost:3000/static/js/18.chunk.js:34017:16)
    at workLoop (http://localhost:3000/static/js/18.chunk.js:34058:28)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/18.chunk.js:13885:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/18.chunk.js:13934:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/18.chunk.js:13988:35)
    at replayUnitOfWork (http://localhost:3000/static/js/18.chunk.js:33241:9)
    at renderRoot (http://localhost:3000/static/js/18.chunk.js:34171:17)
    at performWorkOnRoot (http://localhost:3000/static/js/18.chunk.js:35095:11)
    at performWork (http://localhost:3000/static/js/18.chunk.js:35005:11)
    at performSyncWork (http://localhost:3000/static/js/18.chunk.js:34979:7)
    at interactiveUpdates$1 (http://localhost:3000/static/js/18.chunk.js:35264:11)
    at interactiveUpdates (http://localhost:3000/static/js/18.chunk.js:16006:14)
    at dispatchInteractiveEvent (http://localhost:3000/static/js/18.chunk.js:18823:7)"
```

### Expected behavior
Being able to remove answers without formik throwing

### Reproducible example

https://codesandbox.io/s/eloquent-germain-dxek2

fill the first field, add and answer, fill the answer field, remove the answer then formik throws

### Suggested solution(s)

Consider that the yup error schema can change it's shape, in this case is changing from array to string

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Formik           | 1.5.8
| React            | 16.8.6
| TypeScript       | 3.5.3
| Browser          | Google Chrome 75.03
| npm/Yarn         | yarn 1.16
| Operating System | Mac osx mojave 10.14.15

**Comment by batusai513** [comment]
someone? :(

**Comment by haswalt** [comment]
In my case I can reproduce by having an array field which requires at least 1 entry, validating then adding an entry. I'm using the FieldArray and helpers to add a new entry.

I'm not mutating my validation types, simply adding a child record
