### ISSUE TITLE
values.hasOwnProperty is not a function in v2

### ISSUE THREAD

**Issue by BjoernRave** [jaredpalmer/formik#2138]
When submitting my form before it runs any validation it throws the following error:

```
TypeError: values.hasOwnProperty is not a function
    at prepareDataForValidation (http://localhost:3000/_next/static/development/pages/movements/new.js:103559:16)
    at prepareDataForValidation (http://localhost:3000/_next/static/development/pages/movements/new.js:103571:21)
    at validateYupSchema (http://localhost:3000/_next/static/development/pages/movements/new.js:103545:22)
    at http://localhost:3000/_next/static/development/pages/movements/new.js:102858:83
    at http://localhost:3000/_next/static/development/pages/movements/new.js:102910:84
    at http://localhost:3000/_next/static/development/pages/movements/new.js:102955:12
    at http://localhost:3000/_next/static/development/pages/movements/new.js:103653:24
    at http://localhost:3000/_next/static/development/pages/movements/new.js:103278:12
    at http://localhost:3000/_next/static/development/pages/movements/new.js:103653:24
    at http://localhost:3000/_next/static/development/pages/movements/new.js:103364:5
    at http://localhost:3000/_next/static/development/pages/movements/new.js:103653:24
    at HTMLUnknownElement.callCallback (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:587:14)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:636:16)
    at invokeGuardedCallback (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:691:31)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:705:25)
    at executeDispatch (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:835:3)
    at executeDispatchesInOrder (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:860:5)
    at executeDispatchesAndRelease (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:964:5)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:973:10)
    at forEachAccumulated (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:945:8)
    at runEventsInBatch (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:990:3)
    at runExtractedPluginEventsInBatch (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:1131:3)
    at handleTopLevel (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:6054:5)
    at batchedEventUpdates$1 (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:24652:12)
    at batchedEventUpdates (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:1666:12)
    at dispatchEventForPluginEventSystem (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:6145:5)
    at attemptToDispatchEvent (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:6261:5)
    at dispatchEvent (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:6165:19)
    at unstable_runWithPriority (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:29238:12)
    at runWithPriority$2 (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:12400:10)
    at discreteUpdates$1 (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:24668:12)
    at discreteUpdates (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:1689:12)
    at dispatchDiscreteEvent (http://localhost:3000/_next/static/development/dll/dll_5b0563bdfc01362a831f.js?ts=1576760335824:6132:3)
```
I created a wrapper with formik and this wrapper is not throwing this error on some forms, but on some it is. Not really sure why. 

It works with formik 1.5.8

If you need more info, I am happy to provide. I thought this might be enough, otherwise I can add you as collaborator to my project

**Comment by jaredpalmer** [comment]
Can you create a sandbox to reproduce?

**Comment by emrosenf** [comment]
I'm experiencing this too. Looks like a simple one line fix in `prepareDataForValidation`. [See this issue](https://github.com/FormidableLabs/urql/pull/343)

Change [L1074](https://github.com/jaredpalmer/formik/blob/2151c3e191dbe9b139701ff34791f42b1a3d600a/packages/formik/src/Formik.tsx#L1074)

```typescript
if (values.hasOwnProperty(k)) {
```

To
```typescript
if (Object.prototype.hasOwnProperty.call(values, k)) {
```

**Comment by jaredpalmer** [comment]
Feel free to submit PR. Be sure to reference that urql issue too

**Comment by BjoernRave** [comment]
@emrosenf wow, same PR, same moment 🙌

**Comment by emrosenf** [comment]
Good timing @BjoernRave! Thanks for your hard work @jaredpalmer, Formik is a super useful library!
