### ISSUE TITLE
Regression in 2.4.2 makes the library unusable

### ISSUE THREAD

**Issue by grybykm** [jaredpalmer/formik#3847]
## Bug report

Regression since 2.4.1

### Current Behavior

Formik 2.4.2

```
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:27292:1)
    at scheduleUpdateOnFiber (react-dom.development.js:25475:1)
    at dispatchSetState (react-dom.development.js:17527:1)
    at eval (formik.esm.js:402:1)
    at eval (formik.esm.js:503:1)
```

```
The above error occurred in the <FieldArrayInner> component:

    at FieldArrayInner (webpack-internal:///./node_modules/formik/dist/formik.esm.js:1642:30)
```

### Expected behavior

It should work as in 2.4.1

**Comment by aandronache** [comment]
This issue makes the latest version completely unusable 😞

**Comment by fum4** [comment]
This issue makes the latest version completely unusable indeed 😞

**Comment by Mihai1iMob** [comment]
Indeed, had to revert to `formik@2.3.3` to make it work again. :(
