### ISSUE TITLE
Warning: An unhandled error was caught from submitForm() TypeError: Right-hand side of 'instanceof' is not an object     at formik.esm.js:784:31

### ISSUE THREAD

**Issue by keyurchitroda** [jaredpalmer/formik#3991]
Issue facing :
I cannot submit the form to the dev/production server. 
But in the local code, it is working fine for me.

Warning: An unhandled error was caught from submitForm() TypeError: Right-hand side of 'instanceof' is not an object
   at formik.esm.js:784:31

Version 
"formik": "2.4.6",
"yup": "0.28.5"

![image](https://github.com/user-attachments/assets/57a43022-5ac7-4180-905b-bc05c3ee9a4c)

**Comment by pritesh511** [comment]
Yes, facing same issue today. It is working fine in localhost but not in dev/stage. can anyone please help here.

**Comment by pritesh511** [comment]
@ijacantual If you are using common component in your form like input, search with dropdown  in that if you passing someting pre defined keyword of formik like isError or something which is overiding the formik type. so make sure you are not using that. In my case i am passing isError in my search dropdown component which i have removed and resolved.

**Comment by kostia1st** [comment]
I don't get it. Why is it a warning (read: silenced error) and not a proper error thrown? 

Because of that this issue goes under the radar for any auto-error-reporting mechanisms. I cannot draw any benefits of doing so.
